version: "3"

services:
    runner-1:
        image: cfloriani/github-runner-in-docker:latest
        environment: 
            - AWS_REGION=<<CHANGE-ME>>
            - AWS_ACCESS_KEY=<<CHANGE-ME>>
            - AWS_SECRET_ACCESS=<<CHANGE-ME>>
            - GITHUB_REPO_URL=<<CHANGE-ME>>
            - GITHUB_RUNNER_NAME=runner-1
            - GITHUB_RUNNER_TOKEN=<<CHANGE-ME>>
            - GITHUB_RUNNER_WORKDIR=/runner/work
            - GITHUB_ORG_RUNNER=false
            - GITHUB_LABELS=linux,x64
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./entrypoint.sh:/entrypoint.sh:ro
        entrypoint: /entrypoint.sh

    runner-2:
        image: cfloriani/github-runner-in-docker:latest
        environment: 
            - AWS_REGION=<<CHANGE-ME>>
            - AWS_ACCESS_KEY=<<CHANGE-ME>>
            - AWS_SECRET_ACCESS=<<CHANGE-ME>>
            - GITHUB_REPO_URL=<<CHANGE-ME>>
            - GITHUB_RUNNER_NAME=runner-2
            - GITHUB_RUNNER_TOKEN=<<CHANGE-ME>>
            - GITHUB_RUNNER_WORKDIR=/runner/work
            - GITHUB_ORG_RUNNER=false
            - GITHUB_LABELS=linux,x64
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./entrypoint.sh:/entrypoint.sh:ro
        entrypoint: /entrypoint.sh
