version: "3"

services:
    runner-1:
        build:
            context: .
            args:    
            - AWS_REGION=<<CHANGE-ME>>
            - AWS_ACCESS_KEY=<<CHANGE-ME>>
            - AWS_SECRET_ACCESS=<<CHANGE-ME>>
            - GITHUB_REPO_URL=<<CHANGE-ME>>
            - GITHUB_RUNNER_NAME=runner-1
            - GITHUB_RUNNER_TOKEN=<<CHANGE-ME>>
            - GITHUB_RUNNER_WORKDIR=/runner/work
            - GITHUB_ORG_RUNNER=false
            - GITHUB_LABELS=linux,x64
            - GITHUB_RUNNER_VERSION=2.274.1
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./entrypoint.sh:/entrypoint.sh:ro
            - ./work:/runner/work:rw
        entrypoint: /entrypoint.sh

    runner-2:
        build:
            context: .
            args:    
            - AWS_REGION=<<CHANGE-ME>>
            - AWS_ACCESS_KEY=<<CHANGE-ME>>
            - AWS_SECRET_ACCESS=<<CHANGE-ME>>
            - GITHUB_REPO_URL=<<CHANGE-ME>>
            - GITHUB_RUNNER_NAME=runner-2
            - GITHUB_RUNNER_TOKEN=<<CHANGE-ME>>
            - GITHUB_RUNNER_WORKDIR=/runner/work
            - GITHUB_ORG_RUNNER=false
            - GITHUB_LABELS=linux,x64
            - GITHUB_RUNNER_VERSION=2.274.1
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./entrypoint.sh:/entrypoint.sh:ro
            - ./work:/runner/work:rw
        entrypoint: /entrypoint.sh        
